"""Deterministic local repo wiki generation for Sarathi workspaces."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

GENERATED_MARKER = "<!-- generated by sarathi wiki -->"
REQUIRED_WIKI_PAGES = ("README.md", "architecture.md", "development.md")


def generate_repo_wiki(target_path: str | Path) -> dict[str, Any]:
    """Create or refresh generated wiki pages under ``.sarathi/wiki``.

    Generated files are safe to refresh because they carry ``GENERATED_MARKER``.
    Existing human-authored markdown files are preserved.
    """

    root = Path(target_path).expanduser().resolve()
    root.mkdir(parents=True, exist_ok=True)
    wiki_dir = root / ".sarathi" / "wiki"
    existed_before = wiki_dir.exists()
    wiki_dir.mkdir(parents=True, exist_ok=True)

    inventory = _inventory(root)
    written: list[str] = []
    preserved: list[str] = []
    pages = {
        "README.md": _render_readme(root, inventory),
        "architecture.md": _render_architecture(root, inventory),
        "development.md": _render_development(root, inventory),
    }

    for relative_path, content in pages.items():
        page_path = wiki_dir / relative_path
        if page_path.exists() and not _is_generated(page_path):
            preserved.append(relative_path)
            continue
        page_path.write_text(f"{GENERATED_MARKER}\n{content}", encoding="utf-8")
        written.append(relative_path)

    inventory_path = wiki_dir / "inventory.json"
    inventory_path.write_text(json.dumps(inventory, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    written.append("inventory.json")

    status = (
        "created"
        if not existed_before and not preserved and set(REQUIRED_WIKI_PAGES).issubset(written)
        else "refreshed"
    )
    return {
        "status": status,
        "path": str(wiki_dir),
        "written": written,
        "preserved": preserved,
        "page_count": len(list(wiki_dir.rglob("*.md"))),
    }


def check_repo_wiki(target_path: str | Path) -> dict[str, Any]:
    root = Path(target_path).expanduser().resolve()
    wiki_dir = root / ".sarathi" / "wiki"
    missing = [page for page in REQUIRED_WIKI_PAGES if not (wiki_dir / page).exists()]
    return {
        "ok": not missing,
        "path": str(wiki_dir),
        "missing": missing,
    }


def _is_generated(path: Path) -> bool:
    try:
        return path.read_text(encoding="utf-8", errors="ignore").lstrip().startswith(GENERATED_MARKER)
    except OSError:
        return False


def _inventory(root: Path) -> dict[str, Any]:
    skip_dirs = {".git", ".sarathi", ".ncp", "node_modules", "__pycache__", ".venv", "venv", "dist", "build"}
    file_count = 0
    dir_names: set[str] = set()
    extensions: dict[str, int] = {}
    entry_points: list[str] = []
    for path in root.rglob("*"):
        if any(part in skip_dirs for part in path.relative_to(root).parts):
            continue
        if path.is_dir():
            dir_names.add(str(path.relative_to(root)))
            continue
        if not path.is_file():
            continue
        file_count += 1
        suffix = path.suffix.lower() or "[none]"
        extensions[suffix] = extensions.get(suffix, 0) + 1
        if path.name in {"pyproject.toml", "package.json", "Cargo.toml", "go.mod", "Makefile", "README.md"}:
            entry_points.append(str(path.relative_to(root)))
    return {
        "root": str(root),
        "file_count": file_count,
        "top_directories": sorted(name for name in dir_names if "/" not in name)[:20],
        "extensions": dict(sorted(extensions.items())),
        "entry_points": sorted(entry_points),
    }


def _render_readme(root: Path, inventory: dict[str, Any]) -> str:
    name = root.name or str(root)
    entries = "\n".join(f"- `{entry}`" for entry in inventory["entry_points"]) or "- No standard entry points detected."
    return f"""# {name} Workspace Wiki

This generated wiki gives Sarathi agents a quick offline map of the workspace.

## Entry Points
{entries}

## Shape
- Files indexed: {inventory["file_count"]}
- Top directories: {", ".join(inventory["top_directories"]) if inventory["top_directories"] else "none"}
"""


def _render_architecture(root: Path, inventory: dict[str, Any]) -> str:
    directories = "\n".join(f"- `{name}/`" for name in inventory["top_directories"]) or "- No top-level directories detected."
    return f"""# Architecture Map

Workspace root: `{root}`

## Top-Level Directories
{directories}
"""


def _render_development(root: Path, inventory: dict[str, Any]) -> str:
    extensions = "\n".join(f"- `{ext}`: {count}" for ext, count in inventory["extensions"].items()) or "- No files indexed."
    return f"""# Development Map

## File Types
{extensions}

## Refresh
Run `sarathi wiki {root}` after major structural changes.
"""
